fix lint

diff --git a/students/RabchenyaMaksim/task_02/src/Dockerfile b/students/RabchenyaMaksim/task_02/src/Dockerfile
--- a/students/RabchenyaMaksim/task_02/src/Dockerfile
+++ b/students/RabchenyaMaksim/task_02/src/Dockerfile
@@ -2,9 +2,12 @@
 
 FROM golang:1.25-alpine AS build
 WORKDIR /app
+
 COPY go.mod ./
 RUN go mod download
+
 COPY . .
+
 RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app
 
 FROM gcr.io/distroless/base-debian12
@@ -17,7 +20,9 @@ COPY --from=build /app/app /app/app
 
 EXPOSE 8003
 
+# Исправленный HEALTHCHECK — убрали || exit 1, т.к. в distroless нет shell,
+# а Docker сам считает контейнер unhealthy при non-zero exit code
 HEALTHCHECK --interval=30s --timeout=3s \
-  CMD ["/app/app", "-healthcheck"] || exit 1
+  CMD ["/app/app", "-healthcheck"]
 
 ENTRYPOINT ["/app/app"]
